In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [2]:
employees = pd.read_csv("../data/employees_raw.csv")
regions = pd.read_csv("../data/region_benefit_profiles.csv")

In [3]:
employees.head()

,qemployee_id,age,gender,marital_status,salary,employment_type,region,has_dependents,tenure_years,enrolled,application_date,last_contact_date,last_contact_channel,plan_tier_requested,broker_channel,prior_year_enrolled,legacy_propensity_score,outreach_notes
0,12324,28,Male,Divorced,44047.60,Full-time,West,No,1.4,0,2024-04-14,2024-03-30,SMS,basic,Employer-Sponsored,0,0.104,Spouse covered elsewhere
1,17825,23,Male,Married,80111.28,Full-time,Midwest,Yes,0.5,1,2024-05-09,2024-04-18,Call,STANDARD,Direct,-1,0.874,Requested more time
2,15200,39,Male,Married,69855.65,Full-time,South,Yes,3.4,1,22/06/2024,2024-06-09,none,Silver,Direct,0,0.870,No response to first outreach
3,16690,31,Female,Married,91567.33,Full-time,South,No,1.2,1,2024-08-16,2024-07-29,email,premium plan,Employer-Sponsored,1,0.894,Requested more time
4,17465,42,Female,Single,59861.68,Contract,Midwest,Yes,23.8,0,13/05/2024,2024-05-06,email,Standard,Employer-Sponsored,-1,0.163,Requested more time

In [4]:
regions.head()

,region,n_employees_region,hist_enrollment_rate_region,avg_salary_region,avg_premium_cost_usd,benefits_broker_rating,hr_outreach_capacity,open_enrollment_window_days,state_mandate_level
0,Midwest,2488,0.617,64921.46,595,4.4,469,18,High
1,Northeast,2506,0.612,65008.32,455,3.1,151,38,low
2,South,2424,0.628,65200.49,481,3.3,324,17,MED
3,West,2582,0.613,65007.07,574,4.7,437,28,Low

In [5]:
employees.shape

(10008, 18)

In [6]:
regions.shape

(4, 9)

In [7]:
employees.columns

Index(['qemployee_id', 'age', 'gender', 'marital_status', 'salary',
       'employment_type', 'region', 'has_dependents', 'tenure_years',
       'enrolled', 'application_date', 'last_contact_date',
       'last_contact_channel', 'plan_tier_requested', 'broker_channel',
       'prior_year_enrolled', 'legacy_propensity_score', 'outreach_notes'],
      dtype='object')

In [8]:
regions.columns

Index(['region', 'n_employees_region', 'hist_enrollment_rate_region',
       'avg_salary_region', 'avg_premium_cost_usd', 'benefits_broker_rating',
       'hr_outreach_capacity', 'open_enrollment_window_days',
       'state_mandate_level'],
      dtype='object')

In [9]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10008 entries, 0 to 10007
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   qemployee_id             10008 non-null  int64
 1   age                      10008 non-null  int64
 2   gender                   10008 non-null  object
 3   marital_status           10008 non-null  object
 4   salary                   10008 non-null  float64
 5   employment_type          10008 non-null  object
 6   region                   10008 non-null  object
 7   has_dependents           10008 non-null  object
 8   tenure_years             10008 non-null  float64
 9   enrolled                 10008 non-null  int64
 10  application_date         9289 non-null   object
 11  last_contact_date        10008 non-null  object
 12  last_contact_channel     8823 non-null   object
 13  plan_tier_requested      9482 non-null   object
 14  broker_channel           9538 non-null   object
 15  prior_year_enrolled      10008 non-null  int64
 16  legacy_propensity_score  9100 non-null   float64
 17  outreach_notes           8555 non-null   object
dtypes: float64(3), int64(4), object(11)
memory usage: 1.4+ MB

In [10]:
regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   region                       4 non-null      object
 1   n_employees_region           4 non-null      int64
 2   hist_enrollment_rate_region  4 non-null      float64
 3   avg_salary_region            4 non-null      float64
 4   avg_premium_cost_usd         4 non-null      int64
 5   benefits_broker_rating       4 non-null      float64
 6   hr_outreach_capacity         4 non-null      int64
 7   open_enrollment_window_days  4 non-null      int64
 8   state_mandate_level          4 non-null      object
dtypes: float64(3), int64(4), object(2)
memory usage: 420.0+ bytes

In [13]:
employees.isnull().sum()

qemployee_id                  0
age                           0
gender                        0
marital_status                0
salary                        0
employment_type               0
region                        0
has_dependents                0
tenure_years                  0
enrolled                      0
application_date            719
last_contact_date             0
last_contact_channel       1185
plan_tier_requested         526
broker_channel              470
prior_year_enrolled           0
legacy_propensity_score     908
outreach_notes             1453
dtype: int64

In [14]:
regions.isnull().sum()

region                         0
n_employees_region             0
hist_enrollment_rate_region    0
avg_salary_region              0
avg_premium_cost_usd           0
benefits_broker_rating         0
hr_outreach_capacity           0
open_enrollment_window_days    0
state_mandate_level            0
dtype: int64

In [15]:
employees.duplicated().sum()

np.int64(0)

In [16]:
regions.duplicated().sum()

np.int64(0)

In [18]:
employees["qemployee_id"].duplicated().sum()

np.int64(8)

In [31]:
employees[employees["qemployee_id"].duplicated(keep=False)]

,qemployee_id,age,gender,marital_status,salary,employment_type,region,has_dependents,tenure_years,enrolled,application_date,last_contact_date,last_contact_channel,plan_tier_requested,broker_channel,prior_year_enrolled,legacy_propensity_score,outreach_notes
91,17959,32,Female,Married,54893.19,Contract,West,Yes,2.7,1,2024-02-28,2024-02-16,EMAIL,NaN,Third-Party,0,NaN,Spouse covered elsewhere
288,14868,36,Male,Married,71383.69,Full-time,South,Yes,1.0,1,2024-05-22,2024-05-10,PHONE,Standard,Employer-Sponsored,1,0.846,Requested more time
455,10484,55,Male,Single,65664.82,Full-time,Northeast,No,5.0,0,07/11/2024,2024-11-06,none,STANDARD,Direct,-1,NaN,Attended benefits webinar
1327,13441,36,Male,Married,72902.08,Part-time,West,Yes,0.8,0,2024-06-05,2024-05-29,EMAIL,silver plan,Third-Party,-1,NaN,No response to first outreach
1589,14846,64,Male,Married,50514.16,Full-time,South,Yes,1.6,0,2024-12-25,2024-12-19,NaN,basic,Direct,-1,NaN,Follow-up scheduled
2061,14868,36,Male,Married,71383.69,Full-time,South,Yes,1.0,0,2024-05-22,2024-05-10,PHONE,Standard,Employer-Sponsored,1,NaN,Requested more time
2241,17959,32,Female,Married,54893.19,Contract,West,Yes,2.7,0,2024-02-28,2024-02-16,EMAIL,NaN,Third-Party,0,0.198,Spouse covered elsewhere
4188,10484,55,Male,Single,65664.82,Full-time,Northeast,No,5.0,1,07/11/2024,2024-11-06,none,STANDARD,Direct,-1,NaN,Attended benefits webinar
6139,13840,36,Female,Married,84764.82,Part-time,West,No,1.4,0,04-Sep-2024,2024-08-07,Phone,Silver,Direct,0,0.165,Requested more time
6582,10311,50,Female,Single,57869.86,Full-time,Northeast,Yes,3.1,1,21-Apr-2024,2024-03-29,Email,STANDARD,NaN,1,0.822,Follow-up scheduled
7370,14846,64,Male,Married,50514.16,Full-time,South,Yes,1.6,1,2024-12-25,2024-12-19,NaN,basic,Direct,-1,0.974,Follow-up scheduled
7414,16819,47,Male,Married,78944.56,Full-time,West,Yes,3.4,0,2024-09-29,2024-09-01,NaN,Silver,Direct,1,NaN,Declined - cost concern
7606,13840,36,Female,Married,84764.82,Part-time,West,No,1.4,1,04-Sep-2024,2024-08-07,Phone,Silver,Direct,0,NaN,Requested more time
7698,16819,47,Male,Married,78944.56,Full-time,West,Yes,3.4,1,2024-09-29,2024-09-01,NaN,Silver,Direct,1,0.860,Declined - cost concern
9665,13441,36,Male,Married,72902.08,Part-time,West,Yes,0.8,1,2024-06-05,2024-05-29,EMAIL,silver plan,Third-Party,-1,0.822,No response to first outreach
9835,10311,50,Female,Single,57869.86,Full-time,Northeast,Yes,3.1,0,21-Apr-2024,2024-03-29,Email,STANDARD,NaN,1,NaN,Follow-up scheduled

In [19]:
employees.describe()

,qemployee_id,age,salary,tenure_years,enrolled,prior_year_enrolled,legacy_propensity_score
count,10008.000000,10008.000000,10008.000000,10008.000000,10008.000000,10008.000000,9100.000000
mean,14999.756994,43.003197,65034.633918,3.966447,0.617106,-0.047062,0.605136
std,2886.750141,12.284623,14921.509635,3.894377,0.486117,0.871637,0.363105
min,10001.000000,22.000000,2207.790000,0.000000,0.000000,-1.000000,0.010000
25%,12500.750000,33.000000,54717.165000,1.200000,0.000000,-1.000000,0.191000
50%,14998.500000,43.000000,65063.065000,2.800000,1.000000,0.000000,0.814000
75%,17499.250000,54.000000,75053.687500,5.600000,1.000000,1.000000,0.907000
max,20000.000000,64.000000,120312.000000,36.000000,1.000000,1.000000,0.990000

In [20]:
regions.describe()

,n_employees_region,hist_enrollment_rate_region,avg_salary_region,avg_premium_cost_usd,benefits_broker_rating,hr_outreach_capacity,open_enrollment_window_days
count,4.000000,4.000000,4.000000,4.000000,4.0000,4.00000,4.000000
mean,2500.000000,0.617500,65034.335000,526.250000,3.8750,345.25000,25.250000
std,65.012819,0.007326,117.994929,68.631261,0.7932,143.66251,9.844626
min,2424.000000,0.612000,64921.460000,455.000000,3.1000,151.00000,17.000000
25%,2472.000000,0.612750,64985.667500,474.500000,3.2500,280.75000,17.750000
50%,2497.000000,0.615000,65007.695000,527.500000,3.8500,380.50000,23.000000
75%,2525.000000,0.619750,65056.362500,579.250000,4.4750,445.00000,30.500000
max,2582.000000,0.628000,65200.490000,595.000000,4.7000,469.00000,38.000000

In [21]:
employees.describe(include="object")

,gender,marital_status,employment_type,region,has_dependents,application_date,last_contact_date,last_contact_channel,plan_tier_requested,broker_channel,outreach_notes
count,10008,10008,10008,10008,10008,9289,10008,8823,9482,9538,8555
unique,3,4,3,4,2,1049,390,12,15,3,6
top,Male,Married,Full-time,West,Yes,2024-04-08,2024-10-19,EMAIL,STANDARD,Direct,Declined - cost concern
freq,4820,4595,7046,2586,5999,36,43,1166,1326,3541,1450

In [22]:
regions.describe(include="object")

         region state_mandate_level
count         4                   4
unique        4                   4
top     Midwest                High
freq          1                   1

In [25]:
employees["gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [26]:
employees["marital_status"].unique()

array(['Divorced', 'Married', 'Single', 'Widowed'], dtype=object)

In [27]:
employees["employment_type"].unique()

array(['Full-time', 'Contract', 'Part-time'], dtype=object)

In [28]:
employees["plan_tier_requested"].unique()

array(['basic', 'STANDARD', 'Silver', 'premium plan', 'Standard', 'Basic',
       'silver plan', 'standard', 'BASIC', nan, 'PREMIUM', 'Gold Plan',
       'Bronze', 'gold', 'Premium', 'Gold'], dtype=object)

In [29]:
employees["last_contact_channel"].unique()

array(['SMS', 'Call', 'none', 'email', 'EMAIL', 'e-mail', 'Phone', 'sms',
       'phone', 'Email', nan, 'Text', 'PHONE'], dtype=object)

In [30]:
regions["state_mandate_level"].unique()

array(['High', 'low', 'MED', 'Low'], dtype=object)

In [32]:
employees.describe()

,qemployee_id,age,salary,tenure_years,enrolled,prior_year_enrolled,legacy_propensity_score
count,10008.000000,10008.000000,10008.000000,10008.000000,10008.000000,10008.000000,9100.000000
mean,14999.756994,43.003197,65034.633918,3.966447,0.617106,-0.047062,0.605136
std,2886.750141,12.284623,14921.509635,3.894377,0.486117,0.871637,0.363105
min,10001.000000,22.000000,2207.790000,0.000000,0.000000,-1.000000,0.010000
25%,12500.750000,33.000000,54717.165000,1.200000,0.000000,-1.000000,0.191000
50%,14998.500000,43.000000,65063.065000,2.800000,1.000000,0.000000,0.814000
75%,17499.250000,54.000000,75053.687500,5.600000,1.000000,1.000000,0.907000
max,20000.000000,64.000000,120312.000000,36.000000,1.000000,1.000000,0.990000

In [33]:
employees["salary"].sort_values().head(20)

8425     2207.79
587      5484.33
3821    13376.31
8579    13932.70
5982    16027.53
8610    16593.92
3792    18260.77
2685    18382.70
2182    18396.11
2567    18866.26
1743    18888.35
7589    18935.17
186     19562.61
6429    19569.20
6242    20007.11
3702    20221.06
6120    20674.61
757     20685.34
6479    20710.56
9398    20967.64
Name: salary, dtype: float64

In [34]:
employees["tenure_years"].sort_values(ascending=False).head(20)

4325    36.0
3694    34.7
2813    34.4
2920    33.8
7069    33.2
8584    31.5
3380    27.2
2408    27.2
6504    26.9
6165    26.7
3393    26.5
5110    26.3
1153    26.3
5481    26.0
8470    25.8
5646    25.5
6710    25.5
150     25.2
8660    24.5
2567    24.4
Name: tenure_years, dtype: float64

In [35]:
employees["salary"].sort_values().tail(20)

9955    106880.90
1846    107159.27
3763    107710.61
6611    108368.18
4564    108532.56
2445    108879.21
6363    108945.17
2072    109161.74
2230    109424.90
8831    109908.58
1505    110098.70
2664    111745.22
6035    112101.07
2810    112735.68
5079    112776.42
33      113254.75
4546    115182.12
8094    115733.64
1577    117588.07
3655    120312.00
Name: salary, dtype: float64